@version: 4.2

# Produce log stats every 10 minutes.
options {
    stats(freq(600));
};

# Source to receive logs from remote syslog clients (UDP & TCP).
#   We use `network()` over `syslog()` here as `syslog()` alone handles
#   framing differently which will result in errors and missing data.
# network(transport(tcp) port(514) flags(syslog-protocol));
source s_sys {
    syslog(transport(udp) port(514));
    network(transport(tcp) port(601) flags(syslog-protocol));
};

# Source for syslog-ng's own internal diagnostics.
source s_local {
    internal();
};

# Log destination to forward to Alloy.
# Change "syslog.example.com" to host IP running Alloy and
# adjust syslog port as needed based on your Alloy config.
destination d_alloy {
  syslog("grafana-loki-log-stack-alloy-1" transport("tcp") port(1514));
};


# Ship received syslog messages and syslog-ng internal diagnostics to Alloy.
log {
  source(s_sys);
  source(s_local);
  destination(d_alloy);
};
